baseURL = "https://harmless-upgraded.net/"
languageCode = "en-us"
title = "Harmless, Upgraded"
theme = ["PaperMod"]
paginator.pagerSize = 12
home = "/posts"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  author = "Shane"
  keywords = ["Blog", "PaperMod", "Linux", "Personal"]
  defaultTheme = "auto"
  hideAuthor = false
  disableThemeToggle = false
  contentDir = "content/"
